site_name: Hiring Software Engineers
repo_url: https://github.com/callowayproject/hiring-software-engineers
edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.svg
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - toc.integrate
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
use_directory_urls: true
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - customblocks
  - def_list
  - footnotes
  - md_in_html
  - mdx_truly_sane_lists
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - smarty
  - toc:
      permalink: true
  - tables

plugins:
  - search
  - social
  - git-revision-date-localized
  - git-authors:
      show_email_address: false
  - include-markdown
  - gen-files:
      scripts:
        - docs/gen_doc_stubs.py
  - literate-nav:
      nav_file: SUMMARY.md
  - minify

extra_css:
  - assets/css/extra.css
  - assets/css/mkdocstrings.css
  - assets/css/cards.css
  - assets/css/field-list.css

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Glossary: glossary.md
